<?php
/**
 * Copyright © 2017 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block Spryng\Payment\Block\Adminhtml\Render\Header
 */
?>
<div class="mm-block-spryng">
    <a class="helpbutton" href="https://www.spryngpayments.com/" target="_blank"></a>
    <p>
        <strong>Spryng Payments.</strong>
        This plugin allows you to process payments using CreditCard, iDEAL, PayPal, SOFORT, Klarna and more.
    </p>
    <table>
        <tbody>
        <tr>
            <td>
                <div class="icon1"></div>
                <a href="https://www.spryngpayments.com/" target="_blank">Visit Spryng</a>
            </td>
            <td>
                <div class="icon2"></div>
                <a href="mailto:support@spryngpayments.com">Support</a>
            </td>
            <td>
                <div class="icon3"></div>
                <a href="https://api.spryngpayments.com/" target="_blank">Login to the Dashboard</a>
            </td>
        </tr>
        </tbody>
    </table>
</div>